[project]
name = "flask-prometheus-demo"
version = "0.1.0"
description = "Flask app with Prometheus metrics"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "prometheus-client>=0.22.1",
]

[dependency-groups]
dev = ["ruff>=0.14.4"]
