[project]
name = "flask-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datadog>=0.52.1",
    "ddtrace>=4.0.0",
    "flask>=3.1.2",
]

[dependency-groups]
dev = ["ruff>=0.14.4"]
