name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for builder-config changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            builder:
              - 'builder-config.yaml'
              - 'Dockerfile'
              - 'default-otel-config.yaml'

      - name: Set up Docker Buildx
        if: steps.filter.outputs.builder == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build Otel Collector Image
        if: steps.filter.outputs.builder == 'true'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --cache-to type=gha,mode=max \
            --cache-from type=gha \
            --tag otel-collector:latest \
            --file Dockerfile .
